---
title: HWs
subtitle: ""
author: 
institute: "University of Massachusetts Amherst"
#date: "`r file.mtime(knitr::current_input())`"
output: 
  html_document:
    toc: FALSE
---

PDFs for each HW are provided below, in reverse order. If the pdf links do not work for you, you can find all pdf's in the github repo:  <https://github.com/leontinealkema/bayes/tree/main/docs/hws>

R notebooks and data sets can be downloaded from this <a href="https://drive.google.com/drive/folders/1XX_wfHa89E-0quq3LTmxQ03idkpHTRwP?usp=sharing" target="_blank">Google folder</a>. (This link/set-up will be updated if I figure out an easier way to provide the Rmd's)




### HW3

HW3 without exercise 3

```{r, echo = F}
knitr::include_url('https://leontinealkema.github.io/bayes/hws/hw3_final.pdf')
```

HW3 - exercise 3

```{r, echo = F}
knitr::include_url('https://leontinealkema.github.io/bayes/hws/hw3_exercise3_module7.pdf')
```



### HW2

```{r, echo = F}
knitr::include_url('https://leontinealkema.github.io/bayes/hws/hw2.pdf')
```


### HW1


```{r, echo = F}
knitr::include_url('https://leontinealkema.github.io/bayes/hws/hw1.pdf')
```

