---
title: "Welcome to Applied Bayesian modeling!"
format:
  html:
    link-external-icon: true
    link-external-newwindow: true
---

Welcome to the course website for Applied Bayesian Modeling! This course is taught by Leontine Alkema at UMass Amherst (BIOSTATS 730).

Course information:

-   Course syllabus Fall 2024

-   Course [schedule Fall 2024](https://docs.google.com/spreadsheets/d/1l3c8dZQcqCMiszMAf6XokRncblLy5zc87kMl2fsOnZI/edit?usp=sharing)

Additional course information for enrolled students is on the Canvas course page. We will use a Slack workspace for discussion.

Lecture material (slides, notes, videos) are licensed under CC-BY-NC 4.0. Code is licensed under BSD-3. HWs and exams and their solutions may not be shared without Leontine Alkema's approval.

Thanks to all who helped improve the content of this course! Special thanks for questions, input, and discussions that have shaped and improved the content to past and current students in the Alkema lab and students who participated in prior offerings of Bayesian modeling at UMass Amherst and Berkeley.

Contact: Leontine Alkema (lalkema\@umass.edu)
