---
title: Module 6 - Sampling from posterior densities in Stan
subtitle: ""
#author: Leontine Alkema
institute: "University of Massachusetts Amherst"
#date: "`r file.mtime(knitr::current_input())`"
output: 
  html_document:
     toc_depth: 3
---

### Slides

```{r, echo = F}
knitr::include_url('https://leontinealkema.github.io/bayes/slides/6_sampling_stan.pdf')
```

If the link above doesn't work for you, you can find the pdf file in the github repo:  
<https://leontinealkema.github.io/bayes/slides/6_sampling_stan.pdf>


### Recording

  
```{r, echo = F}
knitr::include_url('https://echo360.org/media/197e23f3-4cdd-4e1b-b579-176afe0f7c63/public')
```


### Code

R notebook can be downloaded from this <a href="https://drive.google.com/drive/folders/1XX_wfHa89E-0quq3LTmxQ03idkpHTRwP?usp=sharing" target="_blank">Google folder</a>. (This link/set-up will be updated if I figure out an easier way to provide the Rmd's)

Knitted pdf is shown here:
```{r, echo = F}
knitr::include_url('https://leontinealkema.github.io/bayes/code/module6.pdf')
```

If the link above doesn't work for you, you can find the pdf file in the github repo:  
<https://leontinealkema.github.io/bayes/code/module6.pdf>