---
title: "Modules"
format:
  html:
    link-external-icon: true
    link-external-newwindow: true
---

# 1 - Introduction

-   Link to [slides](https://umass-my.sharepoint.com/:b:/g/personal/lalkema_umass_edu/EamBX_Oj0AZPs5EP-UU4mXQB8TNldZ2lquLB6-lW2u5x6g)

-   Link to [recording](https://umass-my.sharepoint.com/:v:/g/personal/lalkema_umass_edu/EQXeU01m8PhAtoO-m1ImHJoB9uFc6pvl2OtUnd7HPEVekw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=MyJKns)

# 2 - Bayesian inference for one discrete outcome

-   Link to [slides](https://umass-my.sharepoint.com/:b:/g/personal/lalkema_umass_edu/Ef9SiHIOdqtEvcFkwNcxJyQB5Ngtnqs5QD87FsGNnNWMhg?e=aU8VyT)

-   Link to [recording](https://umass-my.sharepoint.com/:v:/g/personal/lalkema_umass_edu/EZywrcAVZhpDrx8E6CZSBysBLvC_N-rdOH5M1eOimLrR8A?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=tsNxbA)

# 3 - Bayesian inference for one continuous outcome

-   Link to [slides](https://umass-my.sharepoint.com/:b:/g/personal/lalkema_umass_edu/EfFKM6AUc7ZLlvTqlzibf8gBmDTQYdSkcv-n1bBJQ5Fpeg?e=FnMWQK)

-   Link to [recording](https://umass-my.sharepoint.com/:v:/g/personal/lalkema_umass_edu/EdpMLra3ZUVAtC_UWqy2OgoBmdmUGYMfdBO2YtZxunxmNA)

# 4 - Deriving a posterior; bias-variance trade-off

-   Link to [slides](https://umass-my.sharepoint.com/:b:/g/personal/lalkema_umass_edu/EdZYMUlDKEdPqShN0AVodisBl3W84toEy8Jemx-HbXT03A?e=WcZa9R)

-   Link to [recording module 4](https://umass-my.sharepoint.com/:v:/g/personal/lalkema_umass_edu/Ec9Xo1JSNhhHmZcnulDAAtMB8ihDSXNjTdA4qhbtofZmiA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=c1N7P0)

# 5 - Sampling

-   Link to [slides](https://umass-my.sharepoint.com/:b:/g/personal/lalkema_umass_edu/ES7fAj6xiIBOv2ps8jZbWPUBnRlgp7JRbw7QIaQ0h6uf0g?e=Kd53O0)

-   Link to [recording module 5](https://umass-my.sharepoint.com/:v:/g/personal/lalkema_umass_edu/EeLVrkVEOV1NrbJ4j-3RMt8B0rfw8TFRdL3iAV8trEnivg?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=K7ku4C)

# 6 - Sampling from posterior densities in Stan

-   Link to [slides](https://umass-my.sharepoint.com/:b:/g/personal/lalkema_umass_edu/EZb-edMTnjpApCPRXjDYY9AB6pLYnk5jZsqIyEATzaEGeA?e=vpZmAF)

-   Link to [recording module 6](https://umass-my.sharepoint.com/:v:/g/personal/lalkema_umass_edu/EY0lAsElQm9NgDo2-1BPBGcBtNckfMElA3K7Z5R41ar9rQ?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=sIVnYe)

## Instructions on how to get Stan and brms set up

-   If you want “just do this” directions… DO THIS:

    -   Consider updating your R and Rstudio

    -   First install Rstan in 2 steps:

        -   configure your C++ Toolchain, instructions per operating system are here: <https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started#configuring-c-toolchain>

        -   install rstan and verify the installation: <https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started#installing-rstan>

    -   Then install the brms R package; type in your R console: install.packages(“brms")

    -   Then run the code in module6_brms_gettingstarted.Rmd… does it work?

        -   Yes -\> hoorah!

        -   No -\> Check if you missed some steps. If not, get help (in breakout rooms, on our slack)

-   If you want to figure things out for yourself, see <https://github.com/paul-buerkner/brms?tab=readme-ov-file#how-do-i-install-brms> and stan resources.

    -   Note: we will use the latest releases, NOT the developmental versions of code, unless stated otherwise (read: unless we come across a bug that’s been resolved in a developmental version)

# 7 and 8 - Hierarchical (or multilevel) models

In modules 7 and 8, we're going to discuss how to exchange information between populations using hierarchical models, which are also called multilevel models, and fit such models using the brm function.

-   Module 7 [slides](https://umass-my.sharepoint.com/:b:/g/personal/lalkema_umass_edu/ERv8djoD_rdDjCy9a5ayYOQBNDZZt2nBzCCZ2otWzMJgBg?e=zNgf4T) and [recording](https://umass-my.sharepoint.com/:v:/g/personal/lalkema_umass_edu/EYH_zu8bguFNnsMel7NerxIBYwe1geB4bA9_jvviBJs7zw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=UCLcFW)

-   Module 8 [slides](https://umass-my.sharepoint.com/:b:/g/personal/lalkema_umass_edu/EboMuHtYaJRAj3mY_jC0_lUBfY0z5jThL6JWKR9kidRO-g?e=UcKLVO) and [recording](https://umass-my.sharepoint.com/:v:/g/personal/lalkema_umass_edu/EcpihxEcPwlCpH0p2GDT2hcBtlntRxc8dtS0FkYlAWbnZA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=Owprd0)

-   R code in module78_fit_hierarchical.Rmd in the repo

# 9 - Expanding your model universe

-   Link to [slides](https://umass-my.sharepoint.com/:b:/g/personal/lalkema_umass_edu/Ecs9-_WCqp1EsD_2LZPlsAgB3tqXHtWMlKpeOGeWel6lbg?e=Kf0W37)

-   Link to [recording](https://umass-my.sharepoint.com/:v:/g/personal/lalkema_umass_edu/EdycrQ1-Q21AtjZHIb_gEWoBmXWvG3KVr_f1s0jFRqejxQ?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=ggaXbO)

# 11 - Model checking and validation

-   Part 1: Link to [slides](https://umass-my.sharepoint.com/:b:/g/personal/lalkema_umass_edu/EdCWK06_qJBAqP2Q8t1VwxYB6QD3Np17JX2UJKFYsgNtTg?e=KwlSOn) and [recording](https://umass-my.sharepoint.com/:v:/g/personal/lalkema_umass_edu/EcuPnMVZGPlJnS3nMWegfKYBwjIxnMgvSQHMh0euPQRAig?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=g2gkMO)

-   Part 2: Link to [slides](https://umass-my.sharepoint.com/:b:/g/personal/lalkema_umass_edu/Eah4GZHEWqxEmH2unrE1K5sBAabpl3T5iFakftjaW5Skfw?e=Jbimby) and [recording](https://umass-my.sharepoint.com/:v:/g/personal/lalkema_umass_edu/EUTB9jm4v_VAmJzB730UVY4BbKcxtCYgrp20iyGflWRXxA?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=myappA)

# 12 - Bayesian workflow

-   Link to [slides](https://umass-my.sharepoint.com/:b:/g/personal/lalkema_umass_edu/Eeq_1RNTXh5LkjoR9JRnBJoBrKGOu8tj1wcxr3uqFazOFg?e=RLGNpR)

-   Link to [recording](https://umass-my.sharepoint.com/:v:/g/personal/lalkema_umass_edu/EYXPXUY3NLNKsBbYFVPoFzsBR4E8B8mZcWL6mnq27BOb5g?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=tx1eAj)

Supplementary material on priors and how to set them:

-   Link to [slides](https://umass-my.sharepoint.com/:b:/g/personal/lalkema_umass_edu/EVtCMODHS7VIucFUts7-8ZoBx1VTFa4AhMhoGnEAwSp_gQ?e=uafpnc)

-   Link to [recording](https://umass-my.sharepoint.com/:v:/g/personal/lalkema_umass_edu/EU1-8V9CiCpIumGnBYhYBrwBv6afif-MNpt_9_kWiE44-A?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=MLahbj) (except for summary slide)
